/* generated by servant-csharp */
namespace ServantClientBook
{
    #region Prefecture
    public enum Prefecture
    {
        Hokkaido,
        Aomori,
        Iwate,
        Miyagi,
        Akita,
        Yamagata,
        Fukushima,
        Ibaraki,
        Tochigi,
        Gunma,
        Saitama,
        Chiba,
        Tokyo,
        Kanagawa,
        Nigata,
        Toyama,
        Ishikawa,
        Fukui,
        Yamanashi,
        Nagano,
        Gifu,
        Shizuoka,
        Aichi,
        Mie,
        Shiga,
        Kyoto,
        Osaka,
        Hyogo,
        Nara,
        Wakayama,
        Tottori,
        Shimane,
        Okayama,
        Hiroshima,
        Yamaguchi,
        Tokushima,
        Kagawa,
        Ehime,
        Kochi,
        Fukuoka,
        Saga,
        Nagasaki,
        Kumamoto,
        Oita,
        Miyazaki,
        Kagoshima,
        Okinawa,
    }
    #endregion
    #region Gender
    public enum Gender
    {
        Female,
        Male,
    }
    #endregion
    #region CompanyType
    public enum CompanyType
    {
        CO,
        INC,
        COM,
        LLC,
        COLTD,
    }
    #endregion
    #region Category
    public enum Category
    {
        Science,
        Computer,
        Literate,
        Textbook,
        Comics,
        Magazine,
    }
    #endregion
}
